### PR TITLE
Drop the input before writing to the output

### LINKED ISSUE #812: Could not persist output to disk on windows
**Describe the bug**

As reported by a windows user in
https://github.com/blindFS/topiary-nushell/issues/1#issuecomment-2557226561

```
❯ topiary format toolkit.nu
[2024-12-20T15:29:41Z ERROR topiary] Could not persist output to disk
[2024-12-20T15:29:41Z ERROR topiary] Cause: Access is denied. (os error 5)
```

**To Reproduce**
1. manually compile https://github.com/nushell/tree-sitter-nu with `tree-sitter build` on windows
2. specify the dll file path in `languages.ncl`
3. run `topiary format *.nu`

**Expected behavior**
write formatted code back to the input file.

**Environment**
 - OS name + version: windows + latest commit
 - parser also at the latest commit

**Additional context**

### PR DESCRIPTION
**Pull request by Xophmeister**
# Drop the input before writing to the output
Resolves #812

## Description

When Topiary tries to write its output in place, it does so by writing to a temporary file that is then moved to the same location as the input file when it's complete (known as "persisting"). The hypothesis is that Windows opens an exclusive lock on the input file and therefore this process fails.

This PR causes all references to the open input file to be dropped -- and hence the file handler closed -- before persistence.

> [!NOTE]
> This PR also introduces a minimal Windows CI workflow.

## Checklist
Checklist before merging:
- [x] Changes in #830
  - [x] Rebase from `chris/grammar-build`
  - [x] Rebase once merged to `main`
- [x] CHANGELOG.md updated
- [x] README.md up-to-date

### CODE REVIEW

**Comment by Xophmeister** [comment]
Experimentation suggests that building the libraries with Topiary doesn't work on Windows, even if you force it to use the GNU toolchain. `tree-sitter build` demonstrably works, so there are two options at this point:

1. Put together a quick-and-dirty CI workflow for Windows which calls `tree-sitter build` first, to build all the grammars?
2. Implement it properly within Topiary (per #829) and then rebase, allowing for a very simple Windows pipeline?

I think (2) is the obvious choice...but it will take a bit of time.

**Comment by Xophmeister** [comment]
Going with (2) in #830...

**Comment by Xophmeister** [comment]
The good news is that the grammar building changes introduced (and rebased into this branch) in #830 are working on Windows:

```
2025-01-20T15:25:33.3388582Z [2025-01-20T15:22:07Z INFO  topiary_config::language] bash: Language Grammar not found, attempting to fetch and compile it
2025-01-20T15:25:33.3389932Z [2025-01-20T15:22:07Z INFO  topiary_config::language] bash: Cloning from https://github.com/tree-sitter/tree-sitter-bash.git
2025-01-20T15:25:33.3390910Z Cloning into 'C:\Users\RUNNER~1\AppData\Local\Temp\.tmpB8O8TH\bash'...
2025-01-20T15:25:33.3391795Z [2025-01-20T15:22:08Z INFO  topiary_config::language] bash: Checking out d1a1a3fe7189fdab5bd29a54d1df4a5873db5cb1
2025-01-20T15:25:33.3392593Z Note: switching to 'd1a1a3fe7189fdab5bd29a54d1df4a5873db5cb1'.
2025-01-20T15:25:33.3393003Z 
2025-01-20T15:25:33.3393287Z You are in 'detached HEAD' state. You can look around, make experimental
2025-01-20T15:25:33.3393996Z changes and commit them, and you can discard any commits you make in this
2025-01-20T15:25:33.3394665Z state without impacting any branches by switching back to a branch.
2025-01-20T15:25:33.3395105Z 
2025-01-20T15:25:33.3395366Z If you want to create a new branch to retain commits you create, you may
2025-01-20T15:25:33.3396016Z do so (now or later) by using -c with the switch command. Example:
2025-01-20T15:25:33.3396370Z 
2025-01-20T15:25:33.3396535Z   git switch -c <new-branch-name>
2025-01-20T15:25:33.3396779Z 
2025-01-20T15:25:33.3396910Z Or undo this operation with:
2025-01-20T15:25:33.3397180Z 
2025-01-20T15:25:33.3397294Z   git switch -
2025-01-20T15:25:33.3397462Z 
2025-01-20T15:25:33.3397802Z Turn off this advice by setting config variable advice.detachedHead to false
2025-01-20T15:25:33.3398229Z 
2025-01-20T15:25:33.3398376Z HEAD is now at d1a1a3f 0.20.5
2025-01-20T15:25:33.3399202Z [2025-01-20T15:22:08Z INFO  topiary_config::language] bash: Building grammar
2025-01-20T15:25:33.3399988Z [2025-01-20T15:22:10Z INFO  topiary_config::language] bash: Grammar successfully compiled
2025-01-20T15:25:33.3401256Z [2025-01-20T15:22:10Z DEBUG topiary_config::language] Loading grammar from C:\Users\runneradmin\AppData\Local\topiary\cache\bash\d1a1a3fe7189fdab5bd29a54d1df4a5873db5cb1.dll
```

The bad news is that `input_output_tester` and `formatted_query_tester` are panicking, causing the CI to fail. They're panicking because the output and expected output differ (see `topiary-core/src/test_utils.rs`), but the diff output is only showing:

```
...
```

i.e., The context skipping marker, with no actual diffs :shrug:

Best guess: Windows line endings, or no EOF `\n`...but I think that's a long shot.

**Comment by Xophmeister** [comment]
> Best guess: Windows line endings, or no EOF `\n`...but I think that's a long shot.

Bingo!...but it's not in Topiary's output, it's from the Git checkout:

```console
$ md5sum expected.sh formatted.sh
f862ea1582a18bf93dfb1109859a9801  expected.sh
a5259ba2d34f94d028405fe730154ad8  formatted.sh

$ dos2unix -n expected.sh expected-unix.sh
$ md5sum expected-unix.sh formatted.sh
a5259ba2d34f94d028405fe730154ad8  expected-unix.sh
a5259ba2d34f94d028405fe730154ad8  formatted.sh
```

File: topiary-cli/src/main.rs [hunk 1]
```diff
@@ -66,18 +66,26 @@ async fn run() -> CLIResult<()> {
...
+                                    formatter(
+                                        &mut buf_input,
+                                        &mut buf_output,
+                                        &language,
+                                        Operation::Format {
+                                            skip_idempotence,
+                                            tolerate_parsing_errors,
+                                        },
+                                    )?;
+                                }
```
Comment (yannham) [inline topiary-cli/src/main.rs:88]: Another possibility is to `std::mem::drop` the buffer explicitly. For the record; I'm not saying that this is better than the current solution

**Review by yannham — APPROVED** [review]

File: topiary-cli/src/main.rs (hunk 1 above)
Comment (Xophmeister) [reply topiary-cli/src/main.rs:88]: Good to know :pray: That's certainly more explicit than using scopes.
