### PR TITLE
[OCaml] List formatting

### LINKED ISSUE #189: [OCaml] Bad formatting of multiline lists
**Describe the bug**
Formatting of multiline lists is quite poor. This is the output of topiary:
```
let _ =
  [1 ;
  2 ;
  3]
```
**Expected behavior**
I would expect the example above to be formatted in either one of those:
```
let _ = [
  1 ;
  2 ;
  3
]
```
```
let _ =
  [ 1
  ; 2
  ; 3
  ]
```
```
let _ =
  [
    1 ;
    2 ;
    3
  ]
```
```
let _ =
  [ 1 ;
    2 ;
    3
  ]
```

**Environment**
 - Ubuntu 22.04
 - main on 2023-01-24 (https://github.com/tweag/topiary/commit/3eefa610bab865a25adaf93a1046937b85836657)

### PR DESCRIPTION
**Pull request by nbacquey**
Allows proper formatting of
```ocaml
let _ =
  [
    1;
    2;
    3
  ]
```

Ideally, we would want to add a final `;` to multiline lists, but we don't have the capacity to do that yet: see #199.

Closes #189

### CODE REVIEW

File: tests/samples/expected/ocaml.ml [hunk 1]
```diff
@@ -573,6 +573,13 @@ let large_const =
     (long_argument_4 : int) ->
     val
 
+let _ =
+  [
+    1;
+    2;
+    3
```
Comment (aspiwack) [inline tests/samples/expected/ocaml.ml:580]: To the risk of belabouring a point. What I _actually_ expect is:

```suggestion
    1;
    2;
    3;
```

Comment (nbacquey) [reply tests/samples/expected/ocaml.ml:580]: I agree that's the ideal outcome, but we can't have it yet: see #199 
Should I add the issue to the v0.1 milestone?

Comment (aspiwack) [reply tests/samples/expected/ocaml.ml:580]: I added it to the milestone. We can remove it if the conclusion is that we shall not.

For the record: this should definitely be tackled in a separate PR either way. I was making that point because the PR is titled “List formatting”, which would seem to imply that there is no further issue with lists.
