### PR TITLE
Fix edge cases in dangling behaviours

### LINKED ISSUE #914: Idempotency error on
As of c62135d775155b53bb7c1a2a9080769d7c6e9918, Topiary runs into an idempotency error on:

```ocaml
match foo with
| _ ->
  (
    match bar with
    | [] -> None
    | _ -> foo
  )
```

First time round:
```ocaml
match foo with
| _ ->
  (
    match bar with
    | [
    ] -> None
    | _ -> foo
  )
```

Second time round:
```ocaml
match foo with
| _ ->
  (
    match bar with
    | [
    ] ->
      None
    | _ -> foo
  )
```

Somehow, this is my minimal reproducer: removing the outside `match` or the parentheses gets rid of the error.

### LINKED ISSUE #915: Idempotency error on list singleton in nested match
As of https://github.com/tweag/topiary/commit/c62135d775155b53bb7c1a2a9080769d7c6e9918, Topiary runs into an idempotency error on:
```ocaml
match foo with
| _ ->
  (
    if path = [] then
      ()
    else
      ()
  )
```

First time round:
```ocaml
match foo with
| _ ->
  (
    if path = [
        ] then
      ()
    else
      ()
  )
```

Second time round:
```ocaml
match foo with
| _ ->
  (
    if path
      = [
        ] then
      ()
    else
      ()
  )
```

Somehow, this is my minimal reproducer: removing the outside `match` or the parentheses gets rid of the error. This is probably the same as https://github.com/tweag/topiary/issues/914

### LINKED ISSUE #916: Idempotency error on let-binding with type with parameters
As of https://github.com/tweag/topiary/commit/c62135d775155b53bb7c1a2a9080769d7c6e9918, Topiary runs into an idempotency error on:

```ocaml
let foo : (bar, baz) qux =
  ()
```

First time round:
```ocaml
let foo :
    (bar, baz) qux =
  ()
```

Second time round:
```ocaml
let foo
    :
    (bar, baz) qux
  =
  ()
```

I'm not sure why Topiary tries to multi-line this in the first place; I kind of like it as it is; I'd expect Topiary to multi-line my type only if I already make it multi-line.

It has to do with multiple type arguments. The following piece of code has no issue:
```ocaml
let foo : bar qux =
  ()

let foo : qux =
  ()
```
and is formatted as-is.

### LINKED ISSUE #917: “Trying to close an unopened indentation block” on some multi-line list
Sorry for the weird title, I cannot make sense of this one.

As of c62135d775155b53bb7c1a2a9080769d7c6e9918, Topiary fails on:

```ocaml
let _ =
  div
    ~a: [a_id "page_nav"]
    [
      some stuff
    ]
```

with

```
[2025-03-20T09:57:23Z ERROR topiary] Trying to close an unopened indentation block
```

I was initially tracking an idempotency error where Topiary changed identation of the multi-line list at each run. I will share a reproducer for that too later.

This happens with or without `some stuff` in the list, but it does not happen if the list is single-line.

This only happens with that named first argument. It doesn't happen:
- with just a named argument, eg. `div ~a [some stuff]` (but multiline)
- with a named argument pointing to something that is not a list, eg. `div ~a: b [some stuff]`
It does happen no matter what the list give to `~a` is.

### PR DESCRIPTION
**Pull request by nbacquey**
## Description
Closes #914
Closes #915
Closes #916
Closes #917

Also fixes some minor issues with antispace, that did not appear before.

## Checklist

Checklist before merging, wherever relevant:

- [x] `CHANGELOG.md` updated
- [x] Documentation (The Topiary Book, `README.md`, etc.) up-to-date

### CODE REVIEW

File: topiary-cli/tests/samples/expected/ocaml.ml [hunk 1]
```diff
@@ -73,7 +73,7 @@ let create n =
   let n = if n < 1 then 1 else n in
   let n = if n > Sys.max_string_length then Sys.max_string_length else n in
   let s = Bytes.create n in
-  {buffer = s; position = 0; length = n; initial_buffer = s}
+    {buffer = s; position = 0; length = n; initial_buffer = s}
```
Comment (Niols) [inline topiary-cli/tests/samples/expected/ocaml.ml:76]: A bit puzzled by this indentation after a chain of `let ... in`. Is that a side effect or a choice?

File: topiary-cli/tests/samples/expected/ocaml.ml [hunk 2]
```diff
@@ -953,7 +953,7 @@ open Bar
 
 let _ =
   let open Baz in
-  ()
+    ()
```
Comment (Niols) [inline topiary-cli/tests/samples/expected/ocaml.ml:956]: Ditto.

**Review by Niols — APPROVED** [review]
I cannot judge on the state of the query, as always. The OCaml example look good to me. It's very practical that we can just include my snippets in the tests every time!

I am just a bit puzzled by the indentation of objects after a `let .. in`. cf comments.

File: topiary-cli/tests/samples/expected/ocaml.ml [hunk 3]
```diff
@@ -1415,3 +1415,57 @@ type foo = {
...
+  | _ ->
+    (
+      if path = [] then
+          ()
+      else
+          ()
+    )
+
+let foo : (bar, baz) qux =
+    ()
```
Comment (Xophmeister) [inline topiary-cli/tests/samples/expected/ocaml.ml:1440]: Are there meant to be double indents before `()` on lines 1434, 1436 and 1440?

**Review by Xophmeister — APPROVED** [review]
I noticed a few double-indents, but they may be intentional. Otherwise, LGTM :+1:

File: topiary-cli/tests/samples/expected/ocaml.ml (hunk 3 above)
Comment (Niols) [reply topiary-cli/tests/samples/expected/ocaml.ml:1440]: Oh, didn't even catch that one. I feel it might be related to my own comments: a bunch of places where there is one too many indent levels, either because we're expecting only one level (here) or zero (my comments above).

File: topiary-cli/tests/samples/expected/ocaml.ml (hunk 1 above)
Comment (Niols) [reply topiary-cli/tests/samples/expected/ocaml.ml:76]: I don't understand why we want to format # 2 as it is?

Comment (Niols) [reply topiary-cli/tests/samples/expected/ocaml.ml:76]: I mean, those are two very different examples. In one case, we're after the `=` and in one case after the `in`. Independently from what's inside (so it isn't really about records and whatnot), we probably want:

```ocaml
let foo = [something] in
[something not indented]
```

and

```ocaml
let foo =
  [something indented by one level]
in
[something not indented]
```

For records, I guess that's:

```ocaml
let foo = { bar = 1; baz = 2 } in
{ qux = 1; quux = 2 }
```

and

```ocaml
let foo = {
  bar = 1;
  baz = 2;
}
in
{
  qux = 1;
  quux = 2;
}
```

and I think that's rather common OCaml style. So I still don't see why we _want_ something different. (But I'm just missing something I think?)

Maybe your answer lies in your answer to @Xophmeister, namely that it is just too hard to get, so although we want that we will still go for the over-indented version? That is, at this point at least, perfectly fine, imo!

Comment (Niols) [reply topiary-cli/tests/samples/expected/ocaml.ml:76]: Absolutely, the PR definitely improves the situation!

Comment (Niols) [reply topiary-cli/tests/samples/expected/ocaml.ml:76]: In particular, it fixes all the idempotency problem, so we have a working formatter. It's quite a luxury to get to discuss about style!
