### PR TITLE
Do not remove trailing spaces after pretty-printing

### LINKED ISSUE #973: Topiary removes trailing spaces in leaf nodes
**Describe the bug**
Topiary removes trailing white spaces as part of its post-processing pipeline. However, this is done blindly, after all structural information has been lost. In particular, it affect nodes marked as `@leaf` if they happen to span multiple lines in the input, which can change the semantics of the input (typically for string-like nodes).

**To Reproduce**
See https://github.com/tweag/nickel/issues/2224.

**Expected behavior**
I expect that `@leaf` nodes are free from any modification, including trailing spaces removal.

**Additional context**
@aspiwack mentioned the idea of managing a collection of "precious spans" that must be left untouched. The post-processing phase could query this collection to make sure it doesn't modify a precious span.

### PR DESCRIPTION
**Pull request by nbacquey**
Closes #973

Checklist before merging, wherever relevant:

- [x] `CHANGELOG.md` updated
- [x] Documentation (The Topiary Book, `README.md`, etc.) up-to-date

### CODE REVIEW

**Comment by aspiwack** [comment]
Does the testsuite has tests that ensure that superfluous trailing spaces are nevertheless removed?

**Comment by aspiwack** [comment]
> The sample files in the expected directory should have no extra trailing spaces.

Ah, yes, of course. What about trailing white spaces in the input?

**Comment by aspiwack** [comment]
Of course, but if I write

```ocaml
(* two spaces at the end of the next line *)
f = fun x ->  
  x + 57
```

will the trailing white space be removed?

File: topiary-core/src/lib.rs [hunk 1]
```diff
@@ -260,16 +259,18 @@ pub fn formatter(
...
             let rendered = pretty::render(
                 &atoms[..],
-                // Default to "  " is the language has no indentation specified
+                // Default to "  " if the language has no indentation specified
                 language.indent.as_ref().map_or("  ", |v| v.as_str()),
             )?;
-            let trimmed = trim_whitespace(&rendered);
+
+            // Add a final line break if missing
+            let rendered = format!("{}\n", rendered.trim());
```
Comment (Xophmeister) [inline topiary-core/src/lib.rs:267]: This is a niche edge case, but if the input has no EOF `\n` and contains semantic horizontal whitespace at the end of the last line, that will get trimmed.
